# This is an example of the DAITSS configuration file restricted to
# the data necessary to run the xmlresolution service.
#
# You must set up your web server to set the environment variable
# DAITSS_CONFIG to point to a configuration file along these lines,
# though typically it will have sections for many services in addition
# to this one.
#
# Please don't use tabs in this file.

defaults:
     temp_directory:             /var/tmp

database:
     storemaster_db:             postgres://storemaster:topsecret@localhost/storemaster_db

storemaster:
    virtual_hostname:            store-master.example.org
    log_syslog_facility:         LOG_LOCAL0
    log_database_queries:        false
    required_pools:              1

# defaults:temp_directory
# -----------------------
# Where should temporary files be created? This should be at least twice the size of the
# largest package you plan to ingest, plus headroom.  Defaults to system-defined temp directory
# (typically /tmp/)
#
# database:storemaster_db
# -----------------------
# Required, the database connection string for storemaster database
# string.  Supported vendors: postgres. Some fields are optional - for
# instance, if there is no password and you use the postgres default
# port, 5432:
#
#  postgres://username@hostname/database
#
# With port and password it looks like
#
#  vendor://username:password@hostname:port/database" 
#
# N.B.  This means that this config file should have read permissions
# retricted to the user running the service, or an appropriately
# restricted group.
#
# storemaster:log_database_queries
# --------------------------------
# Should we log database queries? defaults to false.  These generate
# very large logs, so it's only recommended for troubleshooting and
# learning.
#
# storemaster:log_syslog_facility
# -------------------------------
# If set, direct log information to this syslog facility (see
# /etc/syslog.conf), otherwise log to STDERR.
#
# storemaster:virtual_hostname
# ----------------------------
# What hostname are we running the service under?  This is used as a
# tag in the logs. Defaults to the hostname of the server
#
# storemaster:required_pools
# --------------------------
# How many pool servers are we required to connect to?  Defaults to 2. Use zero for
# a 'stub server' for testing - in that case, nothing will actually be stored.
