#!/usr/bin/env ruby

require 'optparse'
require 'time'

Struct.new('Config', :server, :silo)

def parse_command args
  conf = Struct::Config.new

  opts   = OptionParser.new do |opt|
    opt.on("--server hostname",  String, "webserver name, e.g. 'storage.local'") do |server|
      conf.server = server
    end
  end
  opts.parse!(args)
  raise "no server specified." unless conf.server
rescue => e
  STDERR.puts "Error in command line options: #{e.message}\n#{opts}"
  exit
else
  return conf
end


conf = parse_command ARGV

ARGV.each do |filename|
  md5 = `md5-base64 #{filename}`.chomp
  id = File.basename(filename).gsub(/\..*$/, '')
  cmd = "curl -sv -X PUT  -H 'Content-Type: application/x-tar' -H 'Content-MD5: #{md5}' --upload-file #{filename} http://#{conf.server}/packages/#{id} 2>&1"
  puts cmd
  puts cmd.gsub(/./, '=')
  puts `#{cmd}`
  puts ''
  puts ''
end
